import pandas as pd
import json

# load the JSON file generated by collect.py
with open("job_offers.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

# convert the list of dictionaries into a Pandas DataFrame
df = pd.DataFrame(raw_data)

# quick inspection
print(df.shape)
print(df.head())
print(df.dtypes)

# convert the Unix timestamp into a readable date
df["created_at"] = pd.to_datetime(df["created_at"], unit="s")

# check for missing values in each column
print(df.isnull().sum())

# check for duplicates based on the offer URL
print(f"Number of duplicate URLs: {df.duplicated(subset='url').sum()}")

# build the companies table (unique company names)
companies_df = df[["company"]].drop_duplicates().reset_index(drop=True)
companies_df["company_id"] = companies_df.index + 1

print(companies_df.head())
print(f"Number of unique companies: {len(companies_df)}")

# build the offers table, linking each offer to its company_id
offers_df = df.merge(companies_df, on="company", how="left")

offers_df["offer_id"] = offers_df.index + 1

offers_df = offers_df[["offer_id", "title", "location", "remote", "created_at", "url", "company_id"]]

print(offers_df.head())
print(f"Number of offers: {len(offers_df)}")