import pandas as pd
import json

# load the JSON file generated by collect.py
with open("job_offers.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

# Step 2: convert the list of dictionaries into a Pandas DataFrame
df = pd.DataFrame(raw_data)

# quick inspection
print(df.shape)
print(df.head())
print(df.dtypes)

# convert the Unix timestamp into a readable date
df["created_at"] = pd.to_datetime(df["created_at"], unit="s")

# check for missing values in each column
print(df.isnull().sum())