import pandas as pd
import json
import sqlite3

# load the JSON file generated by collect.py
with open("job_offers.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

# convert the list of dictionaries into a Pandas DataFrame
df = pd.DataFrame(raw_data)

# quick inspection
print(df.shape)
print(df.head())
print(df.dtypes)

# convert the Unix timestamp into a readable date
df["created_at"] = pd.to_datetime(df["created_at"], unit="s")

# check for missing values in each column
print(df.isnull().sum())

# check for duplicates based on the offer URL
print(f"Number of duplicate URLs: {df.duplicated(subset='url').sum()}")

# build the companies table (unique company names)
companies_df = df[["company"]].drop_duplicates().reset_index(drop=True)
companies_df["company_id"] = companies_df.index + 1

print(companies_df.head())
print(f"Number of unique companies: {len(companies_df)}")

# build the offers table, linking each offer to its company_id
offers_df = df.merge(companies_df, on="company", how="left")

offers_df["offer_id"] = offers_df.index + 1

offers_df = offers_df[["offer_id", "title", "location", "remote", "created_at", "url", "company_id"]]

print(offers_df.head())
print(f"Number of offers: {len(offers_df)}")

# explode the tags column so each tag gets its own row
offer_tags_raw = df[["url", "tags"]].explode("tags")

print(offer_tags_raw.head(10))
print(f"Number of rows after exploding: {len(offer_tags_raw)}")

# build the tags table (unique tag names)
tags_df = offer_tags_raw[["tags"]].drop_duplicates().reset_index(drop=True)
tags_df = tags_df.rename(columns={"tags": "tag_name"})
tags_df["tag_id"] = tags_df.index + 1

print(tags_df.head())
print(f"Number of unique tags: {len(tags_df)}")

# build the offer_tags linking table with real offer_id and tag_id
offer_tags_df = offer_tags_raw.rename(columns={"tags": "tag_name"})

offer_tags_df = offer_tags_df.merge(offers_df[["offer_id", "url"]], on="url", how="left")
offer_tags_df = offer_tags_df.merge(tags_df, on="tag_name", how="left")

offer_tags_df = offer_tags_df[["offer_id", "tag_id"]]

print(offer_tags_df.head(10))
print(f"Number of offer-tag links: {len(offer_tags_df)}")


# load the 4 tables into a SQLite database
connection = sqlite3.connect("job_offers.db")

companies_df.to_sql("companies", connection, if_exists="replace", index=False)
offers_df.to_sql("offers", connection, if_exists="replace", index=False)
tags_df.to_sql("tags", connection, if_exists="replace", index=False)
offer_tags_df.to_sql("offer_tags", connection, if_exists="replace", index=False)

connection.close()

print("Data loaded into job_offers.db")


# run a few SQL queries to verify the database
connection = sqlite3.connect("job_offers.db")

query = """
SELECT offers.title, companies.company, offers.location
FROM offers
JOIN companies ON offers.company_id = companies.company_id
WHERE offers.remote = 1
LIMIT 5
"""

result = pd.read_sql_query(query, connection)
print(result)

connection.close()